// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmFv9V-fQr7GZvc9qYAMaKAJklAh3a78o',
    appId: '1:91482257895:web:0d58117ec2891fd265e542',
    messagingSenderId: '91482257895',
    projectId: 'sleep-coffee-advisor',
    authDomain: 'sleep-coffee-advisor.firebaseapp.com',
    storageBucket: 'sleep-coffee-advisor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxgx8TMxFcQxzzKdt1oHHVsxur3SobqGY',
    appId: '1:91482257895:android:3964bbe25c45b07365e542',
    messagingSenderId: '91482257895',
    projectId: 'sleep-coffee-advisor',
    storageBucket: 'sleep-coffee-advisor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv5fY2MeyJaYJIJWKBpf6LnYXWByKQ1yg',
    appId: '1:91482257895:ios:f36723c65426722f65e542',
    messagingSenderId: '91482257895',
    projectId: 'sleep-coffee-advisor',
    storageBucket: 'sleep-coffee-advisor.firebasestorage.app',
    iosBundleId: 'com.example.sleepCoffeeAdvisor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv5fY2MeyJaYJIJWKBpf6LnYXWByKQ1yg',
    appId: '1:91482257895:ios:f36723c65426722f65e542',
    messagingSenderId: '91482257895',
    projectId: 'sleep-coffee-advisor',
    storageBucket: 'sleep-coffee-advisor.firebasestorage.app',
    iosBundleId: 'com.example.sleepCoffeeAdvisor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmFv9V-fQr7GZvc9qYAMaKAJklAh3a78o',
    appId: '1:91482257895:web:bac1527d19c242c565e542',
    messagingSenderId: '91482257895',
    projectId: 'sleep-coffee-advisor',
    authDomain: 'sleep-coffee-advisor.firebaseapp.com',
    storageBucket: 'sleep-coffee-advisor.firebasestorage.app',
  );

}